name: MacOS

on:
  push:
    branches-ignore: develop
  pull_request:
    branches-ignore: develop

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./ci_scripts/ci_macos_build.sh  
    - name: Test
      run: ./ci_scripts/ci_macos_test.sh
    - name: InstallTest
      run: ./ci_scripts/ci_macos_install_test.sh
